package by.epam.tc.parser.sax;

public enum MenuTagNameSAX {
	COLD_APPETIZER, HOT_APPETIZER, BREAKFAST, NAME, DESCRIPTION, PRICE, PORTION,
	COLD_APPETIZERS,HOT_APPETIZERS, BREAKFASTS,MMENU_LIST;
}
